### ISSUE TITLE
ایجاد api Film

### ISSUE THREAD

**Issue by mehdi1361** [mehdi1361/orm#42]
<div dir="rtl">
<ul>
    <li>یک api برای نمایش فیلم ها ایجاد شود</li>
     <li> آدرس دسترسی به api  به صورت 
            <br>
                server_url/api/v1/movie/film/2
            <br>
            باشد
     </li>
    <li>عدد آخر در url  باید شماره صفحه باشد یعنی در هر صفحه فقط ۳۰ فیلم نمایش داده شود و pagination انجام شود.به طور مثال اگر در 
        url عدد ۳ باشد باید ۳۰ فیلم سوم را نمایش دهد.</li>
    <li> برای راهنمایی پیاده سازی بالا <a href="https://docs.djangoproject.com/en/3.1/topics/db/queries/#limiting-querysets">کلیک کنید</a></li>
    <li> مثال خروجی برای api در پیوست می باشد
</ul>
</div>

[generated.txt](https://github.com/mehdi1361/orm/files/5565187/generated.txt)

**Comment by mehdi1361** [comment]
**زمان انجام تسک ۴ ساعت**
**ساعت ۵ امروز پنج شنبه تحویل شود**

**Comment by mirmohsen1367** [comment]
برو بابا
