### ISSUE TITLE
apiبرای کشورها

### ISSUE THREAD

**Issue by mehdi1361** [mehdi1361/orm#9]
<div dir="rtl" align="right">
پیاده سازی api برای دریافت لیست کشورها طبق
<br>
</div>
[wiki](http://193.37.213.206:5000/fa/home/api/country)

**Comment by mehdi1361** [comment]
> پیاده سازی api برای دریافت لیست کشورها طبق
> [wiki](http://193.37.213.206:5000/fa/home/api/country)

[wiki](http://193.37.213.206:5000/fa/home/api/country)

**Comment by mirmohsen1367** [comment]
i sstart studing for task
